/**
 * Default help method of bd_mailer
 *
 * usage : display help informations
 *          relative to bd_mailer
 * args : <h> <help> <-h> <-help>
 *         <--help>
 *
 */
import {ask} from "../configs/parameters.js";

const help = () => {
    console.log(
        '🎉 Birthday Mailer CLI - Automated Birthday Messages\n',
        '═══════════════════════════════════════════════════\n',
        '\n',
        'USAGE: bd_mailer [--help] [--info] [--version] <command> [<args>]\n',
        '\n',
        '⚡ CURRENT FEATURES:\n',
        '\t ✅ Gmail Integration (HTML & Text emails)\n',
        '\t ✅ Automatic Birthday Scheduling (Daily at 9:00 AM)\n',
        '\t ✅ Personalized Birthday Messages\n',
        '\t ✅ Secure App Password Authentication\n',
        '\t ✅ Cross-platform Support (Linux/WSL/Mac)\n',
        '\t ✅ Email Logs & History Tracking\n',
        '\t ✅ Interactive CLI Configuration\n',
        '\t ✅ Email Testing & Validation\n',
        '\n',
        '🚧 FUTURE IMPLEMENTATIONS:\n',
        '\t 🔜 Telegram Bot Integration\n',
        '\t 🔜 WhatsApp Automation\n',
        '\t 🔜 SMS Support (via Twilio)\n',
        '\t 🔜 Multiple Recipients Management\n',
        '\t 🔜 Calendar Integration (.ics export)\n',
        '\t 🔜 Desktop Notifications\n',
        '\t 🔜 Custom Time Scheduling\n',
        '\t 🔜 Birthday Reminder Templates\n',
        '\n',
        '🎯 CONFIGURATION WORKFLOW (IMPORTANT!):\n',
        '\t 📋 STEP 1: Personal Setup\n',
        '\t\t config                Configure your information (REQUIRED)\n',
        '\t\t config list           Verify your setup\n',
        '\n',
        '\t 🎂 STEP 2: Gmail Setup\n',
        '\t\t • Create .env file with Gmail credentials\n',
        '\t\t • Get App Password from Google Account\n',
        '\t\t email test            Test Gmail connection\n',
        '\n',
        '\t 👥 STEP 3: Recipient Setup\n',
        '\t\t to                    Configure recipient details (REQUIRED)\n',
        '\t\t set date              Set birthday date (REQUIRED)\n',
        '\t\t to list               Verify recipient setup\n',
        '\n',
        '\t 💌 STEP 4: Message Setup\n',
        '\t\t set msg               Create birthday message\n',
        '\t\t to msg                Preview your message\n',
        '\n',
        '\t ✅ STEP 5: Testing & Launch\n',
        '\t\t status                Check overall configuration\n',
        '\t\t email send            Send test birthday email\n',
        '\t\t schedule start        Enable automatic sending\n',
        '\n',
        '📋 ALL AVAILABLE COMMANDS:\n',
        '\n',
        '🔧 SETUP & CONFIGURATION:\n',
        '\t config                Configure your personal information\n',
        '\t config list           Show your configured information\n',
        '\t to                    Configure recipient\'s details\n',
        '\t to list               Show recipient\'s information\n',
        '\t to msg                Display saved birthday message\n',
        '\n',
        '✉️  MESSAGE & CONTENT:\n',
        '\t set msg               Create/edit birthday message\n',
        '\t set date              Set recipient\'s birthday date\n',
        '\n',
        '📧 EMAIL COMMANDS:\n',
        '\t email send            Send birthday email immediately\n',
        '\t email test            Test email configuration\n',
        '\t email status          Show email setup status\n',
        '\t send                  Quick send birthday email (shortcut)\n',
        '\n',
        '⏰ SCHEDULER COMMANDS:\n',
        '\t schedule start        Start automatic birthday checking\n',
        '\t schedule stop         Stop the scheduler\n',
        '\t schedule status       Show scheduler status\n',
        '\t schedule test         Test birthday check manually\n',
        '\t schedule logs         Show birthday email logs\n',
        '\t schedule clear        Clear birthday logs\n',
        '\n',
        '📊 INFORMATION & STATUS:\n',
        '\t list                  List friend\'s information\n',
        '\t status                See current configuration status\n',
        '\t help                  Show this help message\n',
        '\t info                  Show detailed program information\n',
        '\t version               Show version number\n',
        '\n',
        '🚀 QUICK START (First Time Users):\n',
        '\t 1. bd_mailer config           # Configure your info (MUST DO FIRST!)\n',
        '\t 2. bd_mailer to               # Set up recipient\n',
        '\t 3. bd_mailer set date         # Set birthday date\n',
        '\t 4. bd_mailer set msg          # Write message\n',
        '\t 5. bd_mailer email test       # Test email setup\n',
        '\t 6. bd_mailer send             # Send birthday email!\n',
        '\t 7. bd_mailer schedule start   # Enable automation\n',
        '\n',
        '💡 TIPS:\n',
        '\t • Use Gmail App Password (not regular password)\n',
        '\t • Run "bd_mailer status" to check overall setup\n',
        '\t • Configuration is the most important first step!\n',
        '\t • Test email before enabling scheduler\n',
        '\t • Use scheduler for hands-off automation\n',
        '\n',
        '📚 EXAMPLES:\n',
        '\t bd_mailer config              # Interactive personal setup\n',
        '\t bd_mailer to                  # Interactive recipient setup\n',
        '\t bd_mailer email test          # Test Gmail connection\n',
        '\t bd_mailer send                # Send birthday email now\n',
        '\t bd_mailer schedule start      # Start auto-checking\n',
        '\t bd_mailer schedule status     # Check if scheduler running\n',
        '\t bd_mailer status              # Overall system status\n',
        '\n',
        '🔗 For detailed setup guide: bd_mailer info\n'
    );
    ask.close();
};

export {help};